// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Solution.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20200207170747_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cats");

                    b.Property<string>("Dogs");

                    b.Property<int>("Quantity");

                    b.HasKey("AnimalId");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            AnimalId = 121,
                            Cats = "Bengal",
                            Dogs = "Corgi",
                            Quantity = 3
                        },
                        new
                        {
                            AnimalId = 131,
                            Cats = "Ragdoll",
                            Dogs = "Lab",
                            Quantity = 1
                        },
                        new
                        {
                            AnimalId = 141,
                            Cats = "Birman",
                            Dogs = "Retriever",
                            Quantity = 2
                        },
                        new
                        {
                            AnimalId = 151,
                            Cats = "Persian",
                            Dogs = "Husky",
                            Quantity = 4
                        },
                        new
                        {
                            AnimalId = 161,
                            Cats = "Sphynx",
                            Dogs = "Chihuahua",
                            Quantity = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
